name: 'Remove old artifacts'
description: 'Remove old artifacts to save space'
inputs:
  leaveNewest:  # id of input
    description: 'Shoulde last be remove'
    required: true
    default: false
  repo-token:
    description: 'Token required to list and delete artifacts'
    required: true
    default: "ERROR"
runs:
  using: 'node12'
  main: 'index.js'