name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  leaveNewest:  # id of input
    description: 'Shoulde last be remove'
    required: true
    default: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'